/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    BaseCards: typeof import('./components/BaseCards.vue')['default']
    ChartTop: typeof import('./components/chartTop.vue')['default']
    GridComponent: typeof import('./components/GridComponent.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    IncomeBudget: typeof import('./components/incomeBudget.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    Keyboard: typeof import('./components/keyboard.vue')['default']
    QiunDataChartsQiunDataCharts: typeof import('./components/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunErrorQiunError: typeof import('./components/qiun-error/qiun-error.vue')['default']
    QiunLoadingLoading1: typeof import('./components/qiun-loading/loading1.vue')['default']
    QiunLoadingLoading2: typeof import('./components/qiun-loading/loading2.vue')['default']
    QiunLoadingLoading3: typeof import('./components/qiun-loading/loading3.vue')['default']
    QiunLoadingLoading4: typeof import('./components/qiun-loading/loading4.vue')['default']
    QiunLoadingLoading5: typeof import('./components/qiun-loading/loading5.vue')['default']
    QiunLoadingQiunLoading: typeof import('./components/qiun-loading/qiun-loading.vue')['default']
    Tabbar: typeof import('./components/Tabbar.vue')['default']
    UserSelect: typeof import('./components/UserSelect.vue')['default']
  }
}
