/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogos: typeof import('./components/AppLogos.vue')['default']
    BaseCards: typeof import('./components/BaseCards.vue')['default']
    Demo: typeof import('./components/Demo.vue')['default']
    HiCounter: typeof import('./components/HiCounter.vue')['default']
    InputEntry: typeof import('./components/InputEntry.vue')['default']
    Keyboard: typeof import('./components/keyboard.vue')['default']
    Tabbar: typeof import('./components/Tabbar.vue')['default']
    UserSelect: typeof import('./components/UserSelect.vue')['default']
  }
}
